name: Docker Image
on: [workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        provenance: false
        tags: "${{ steps.login-ecr.outputs.registry }}/kittenbot:${{ github.sha }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
